export const FAMILY_MILESTONE_KEYS = [
  'FAMILY_ACTIVE_DAYS',
  'FAMILY_RECORD_COUNT',
  'FAMILY_ANNIVERSARY',
] as const;

export const HIDDEN_ACHIEVEMENT_KEYS = [
  'HIDDEN_DISHES_3',
  'HIDDEN_SHINY_FLOOR',
  'HIDDEN_GUESTS',
  'HIDDEN_NIGHT_SHIFT',
  'HIDDEN_ENDURANCE',
] as const;

export const STAGE_SEVEN_VISIBLE_KEYS = [...FAMILY_MILESTONE_KEYS] as const;
