export const REACTION_ACHIEVEMENT_KEYS = [
  'REACTION_FIRST',
  'REACTION_GIVEN_20',
  'REACTION_RECEIVED_10',
] as const;
export const FAMILY_COLLABORATION_KEYS = [
  'FAMILY_FORMED',
  'FAMILY_ALL_IN',
  'FAMILY_RELAY',
  'FAMILY_VISIBLE_4W',
  'FAMILY_FULL_SERVICE',
  'FAMILY_CATEGORY_COVERAGE',
] as const;

export const PAIR_ACHIEVEMENT_KEYS = ['PAIR_COOK_AND_CLEAN'] as const;

export const STAGE_SIX_BOND_KEYS = [
  ...REACTION_ACHIEVEMENT_KEYS,
  ...FAMILY_COLLABORATION_KEYS,
  ...PAIR_ACHIEVEMENT_KEYS,
] as const;
