// Stable IDs are retained for existing records, but every catalog chore is free.
export const additionalChoreCatalog = [
  {
    id: 'premium-change-bedding',
    themeKey: 'daily',
    name: '换床单',
    category: '洗护',
    standardMinutes: 20,
    difficultyMultiplier: 1.2,
    defaultPoints: 24,
    icon: 'bed.double.fill',
  },
  {
    id: 'premium-clean-stove',
    themeKey: 'daily',
    name: '清理灶台',
    category: '清洁',
    standardMinutes: 10,
    difficultyMultiplier: 1.1,
    defaultPoints: 11,
    icon: 'flame.fill',
  },
  {
    id: 'premium-heavy-lifting',
    themeKey: 'daily',
    name: '搬重物',
    category: '家庭事务',
    standardMinutes: 20,
    difficultyMultiplier: 1.6,
    defaultPoints: 32,
    icon: 'chore_catalog_heavy_lifting',
  },
  {
    id: 'premium-clean-litter',
    themeKey: 'pet',
    name: '清理猫砂',
    category: '清洁',
    standardMinutes: 10,
    difficultyMultiplier: 1.2,
    defaultPoints: 12,
    icon: 'chore_catalog_clean_litter',
  },
  {
    id: 'premium-walk-dog',
    themeKey: 'pet',
    name: '遛狗',
    category: '照顾',
    standardMinutes: 30,
    difficultyMultiplier: 1.1,
    defaultPoints: 33,
    icon: 'pawprint.fill',
  },
  {
    id: 'premium-homework-help',
    themeKey: 'childcare',
    name: '陪写作业',
    category: '照顾',
    standardMinutes: 60,
    difficultyMultiplier: 1.5,
    defaultPoints: 90,
    icon: 'chore_catalog_homework_help',
  },
  {
    id: 'premium-repair-booking',
    themeKey: 'daily',
    name: '预约维修',
    category: '家庭事务',
    standardMinutes: 15,
    difficultyMultiplier: 1.1,
    defaultPoints: 17,
    icon: 'chore_catalog_repair_booking',
  },
  {
    id: 'premium-feed-baby',
    themeKey: 'childcare',
    name: '喂奶',
    category: '照顾',
    standardMinutes: 25,
    difficultyMultiplier: 1.5,
    defaultPoints: 38,
    icon: 'chore_catalog_feed_baby',
  },
  {
    id: 'premium-walk-child',
    themeKey: 'childcare',
    name: '遛娃',
    category: '照顾',
    standardMinutes: 45,
    difficultyMultiplier: 1.4,
    defaultPoints: 63,
    icon: 'chore_catalog_walk_child',
  },
  {
    id: 'premium-school-run',
    themeKey: 'childcare',
    name: '接送孩子',
    category: '照顾',
    standardMinutes: 40,
    difficultyMultiplier: 1.4,
    defaultPoints: 56,
    icon: 'chore_catalog_school_run',
  },
] as const;

export type AdditionalChoreDefinition = (typeof additionalChoreCatalog)[number];
