export const themedChoreCatalog = [
  {
    id: 'child-diaper-change',
    themeKey: 'childcare',
    name: '换尿布',
    category: '照顾',
    standardMinutes: 10,
    difficultyMultiplier: 1.2,
    defaultPoints: 12,
    icon: 'chore_theme_child_diaper',
  },
  {
    id: 'child-bath-time',
    themeKey: 'childcare',
    name: '宝宝洗澡',
    category: '洗护',
    standardMinutes: 20,
    difficultyMultiplier: 1.4,
    defaultPoints: 28,
    icon: 'chore_theme_child_bath',
  },
  {
    id: 'child-food-prep',
    themeKey: 'childcare',
    name: '准备辅食',
    category: '烹饪',
    standardMinutes: 30,
    difficultyMultiplier: 1.3,
    defaultPoints: 39,
    icon: 'chore_theme_child_food',
  },
  {
    id: 'child-bedtime',
    themeKey: 'childcare',
    name: '哄睡',
    category: '照顾',
    standardMinutes: 30,
    difficultyMultiplier: 1.5,
    defaultPoints: 45,
    icon: 'chore_theme_child_sleep',
  },
  {
    id: 'pet-feeding',
    themeKey: 'pet',
    name: '宠物喂食',
    category: '照顾',
    standardMinutes: 10,
    difficultyMultiplier: 1,
    defaultPoints: 10,
    icon: 'chore_theme_pet_feeding',
  },
  {
    id: 'pet-bath',
    themeKey: 'pet',
    name: '宠物洗澡',
    category: '洗护',
    standardMinutes: 25,
    difficultyMultiplier: 1.3,
    defaultPoints: 33,
    icon: 'chore_theme_pet_bath',
  },
  {
    id: 'pet-medicine',
    themeKey: 'pet',
    name: '宠物喂药',
    category: '照顾',
    standardMinutes: 10,
    difficultyMultiplier: 1.4,
    defaultPoints: 14,
    icon: 'chore_theme_pet_medicine',
  },
  {
    id: 'pet-vet-visit',
    themeKey: 'pet',
    name: '宠物看诊',
    category: '照顾',
    standardMinutes: 60,
    difficultyMultiplier: 1.4,
    defaultPoints: 84,
    icon: 'chore_theme_pet_vet',
  },
  {
    id: 'love-date-plan',
    themeKey: 'love',
    name: '约会策划',
    category: '家庭事务',
    standardMinutes: 30,
    difficultyMultiplier: 1.1,
    defaultPoints: 33,
    icon: 'chore_theme_love_date',
  },
  {
    id: 'love-gift-prepare',
    themeKey: 'love',
    name: '准备礼物',
    category: '家庭事务',
    standardMinutes: 45,
    difficultyMultiplier: 1.2,
    defaultPoints: 54,
    icon: 'chore_theme_love_gift',
  },
  {
    id: 'love-reunion',
    themeKey: 'love',
    name: '异地见面',
    category: '照顾',
    standardMinutes: 60,
    difficultyMultiplier: 1.2,
    defaultPoints: 72,
    icon: 'chore_theme_love_reunion',
  },
  {
    id: 'love-pickup',
    themeKey: 'love',
    name: '接送对方',
    category: '家庭事务',
    standardMinutes: 40,
    difficultyMultiplier: 1.3,
    defaultPoints: 52,
    icon: 'chore_theme_love_pickup',
  },
  {
    id: 'love-cook-meal',
    themeKey: 'love',
    name: '为你做饭',
    category: '烹饪',
    standardMinutes: 45,
    difficultyMultiplier: 1.4,
    defaultPoints: 63,
    icon: 'chore_theme_love_cook',
  },
  {
    id: 'love-support',
    themeKey: 'love',
    name: '情绪陪伴',
    category: '照顾',
    standardMinutes: 30,
    difficultyMultiplier: 1.2,
    defaultPoints: 36,
    icon: 'chore_theme_love_support',
  },
  {
    id: 'love-anniversary',
    themeKey: 'love',
    name: '纪念日准备',
    category: '家庭事务',
    standardMinutes: 60,
    difficultyMultiplier: 1.3,
    defaultPoints: 78,
    icon: 'chore_theme_love_anniversary',
  },
  {
    id: 'love-trip-plan',
    themeKey: 'love',
    name: '旅行规划',
    category: '家庭事务',
    standardMinutes: 45,
    difficultyMultiplier: 1.2,
    defaultPoints: 54,
    icon: 'chore_theme_love_trip',
  },
  {
    id: 'daily-dust-surfaces',
    themeKey: 'daily',
    name: '擦桌除尘',
    category: '清洁',
    standardMinutes: 15,
    difficultyMultiplier: 1,
    defaultPoints: 15,
    icon: 'chore_custom_dust',
  },
  {
    id: 'daily-clean-windows',
    themeKey: 'daily',
    name: '擦窗玻璃',
    category: '清洁',
    standardMinutes: 30,
    difficultyMultiplier: 1.3,
    defaultPoints: 39,
    icon: 'chore_custom_window',
  },
  {
    id: 'daily-make-bed',
    themeKey: 'daily',
    name: '整理床铺',
    category: '整理',
    standardMinutes: 10,
    difficultyMultiplier: 1,
    defaultPoints: 10,
    icon: 'chore_custom_bed',
  },
  {
    id: 'love-care-plants',
    themeKey: 'daily',
    name: '浇花养护',
    category: '照顾',
    standardMinutes: 10,
    difficultyMultiplier: 0.8,
    defaultPoints: 8,
    icon: 'chore_custom_plant',
  },
  {
    id: 'pet-general-care',
    themeKey: 'pet',
    name: '宠物照料',
    category: '照顾',
    standardMinutes: 15,
    difficultyMultiplier: 1.1,
    defaultPoints: 17,
    icon: 'chore_custom_pet',
  },
  {
    id: 'daily-wash-car',
    themeKey: 'daily',
    name: '清洗车辆',
    category: '清洁',
    standardMinutes: 40,
    difficultyMultiplier: 1.4,
    defaultPoints: 56,
    icon: 'chore_custom_car',
  },
  {
    id: 'daily-clean-fridge',
    themeKey: 'daily',
    name: '清理冰箱',
    category: '清洁',
    standardMinutes: 30,
    difficultyMultiplier: 1.3,
    defaultPoints: 39,
    icon: 'chore_custom_fridge',
  },
  {
    id: 'daily-home-repair',
    themeKey: 'daily',
    name: '家庭维修',
    category: '家庭事务',
    standardMinutes: 30,
    difficultyMultiplier: 1.5,
    defaultPoints: 45,
    icon: 'chore_custom_repair',
  },
  {
    id: 'child-quality-time',
    themeKey: 'childcare',
    name: '陪伴孩子',
    category: '照顾',
    standardMinutes: 30,
    difficultyMultiplier: 1.2,
    defaultPoints: 36,
    icon: 'chore_custom_childcare',
  },
  {
    id: 'daily-home-admin',
    themeKey: 'daily',
    name: '家庭管理',
    category: '家庭事务',
    standardMinutes: 20,
    difficultyMultiplier: 1.1,
    defaultPoints: 22,
    icon: 'chore_custom_admin',
  },
] as const;

export type ThemedChoreDefinition = (typeof themedChoreCatalog)[number];
