// Review-only content. The approved production content remains in content.mjs.
export function reviewPages(c, en) {
  const privacy = en ? [
    ['Your information', 'You can configure a trial household and record chores on your device without signing in. Signing in and upgrading that household uploads its configuration and records to your account. Unsynced data may be lost if you uninstall the app.', 'Email addresses, verification challenges and their digests, Apple identifiers and authorization credentials support authentication and account security. Names, household roles and preset avatars identify members in the interface, not account ownership.', 'Household names, memberships, invitations, chore details, timestamps, duration, points, multipliers, notes, reactions, achievements and layouts support household collaboration and reports. Session identifiers, device descriptions, token digests, request IP addresses, timestamps and necessary error information support communications, sessions and security. Avoid putting sensitive information in notes.'],
    ['Visible to your household', 'Members can see household activity, member names and avatars, duration, points and reports according to their permissions. The household owner manages membership and records. The achievement visibility switch controls achievements, not chore activity. Email addresses and login credentials are not displayed in activity.', 'Share invitations only with people you trust. Content you export through system sharing is delivered to the app or recipient you choose. Leaving a household does not delete your account or necessarily remove historical shared records.'],
    ['Service providers', 'Alibaba Cloud hosts the backend and database in Beijing, mainland China. Its email service receives the destination email address, verification email content and necessary delivery information. Your email provider also processes that message.', 'Apple handles Sign in with Apple and returns authorization results. Login tokens are stored in system Keychain. The app currently has no advertising-tracking SDK; this website has no advertising, analytics or external fonts.', 'Voice input and paid Apple subscriptions are not yet available. Audio is not collected for a voice-input feature. We will explain data handling, update this policy and request necessary permissions before enabling new features. Apple authentication, email delivery and user-selected sharing may involve processing outside mainland China.'],
    ['Storage and retention', 'Account and household data is retained while your account exists and as necessary to provide collaboration. Account deletion immediately removes account identities, sessions and personal records from the live database; necessary shared participation references are anonymized. Legal obligations or necessary dispute handling may require additional retention.', 'Email verification codes expire after 10 minutes. Challenge records, expired or revoked sessions and token digests are periodically cleaned up according to the shortest necessary retention period. Network operation and security logs are retained for at least six months as required by applicable law, then deleted or anonymized.', 'Database backups roll off within 30 days. Deleted data remaining in a backup is used only for disaster recovery, not normal business use. If a backup is restored, the deletion or anonymization is reapplied.', 'HTTPS, session revocation, verification-code digests and encryption of authorization credentials help protect data. No system can guarantee absolute security.'],
    ['Your choices and account deletion', 'In the app you can edit your profile, edit or delete authorized records, control achievement visibility, leave a household and sign out of one or all devices. Signing out does not delete your account.', 'To permanently delete your account: Profile → Account & Security → Delete Account. Identities, sessions, personal records and associated data are removed; necessary participation references in shared achievements are anonymized. Ownership transfers to another active member, or the household is deleted when no other active member remains. Local tokens, caches and pending records are cleared. This cannot be undone.', 'Contact us to request access, correction, a copy, deletion or withdrawal of consent. We will verify only the information needed to handle your request. Deleting an app account does not cancel an Apple subscription; once subscriptions become available, purchasers must manage them through Apple.'],
    ['Children and policy changes', 'This service is not intended for children to register independently. Children under 14 should use it with their guardian’s informed consent and guidance. Do not add unnecessary child identity, school or location details to shared notes. Contact us about information processed without appropriate consent.', 'Material changes affecting your rights will be communicated in the app. We will seek renewed consent when required.'],
    ['Who to contact', `Personal information controller: ${c.operator}. Contact: ${c.supportEmail}. Do not send passwords, verification codes or full identity documents.`],
  ] : [
    ['我们处理的信息', '无需登录即可在本机配置体验家庭、选择家务并记录。登录并升级家庭后，配置和记录会上传至账号。卸载 App 可能导致未同步数据丢失。', '邮箱、验证码挑战及摘要、Apple 稳定标识和授权凭据用于登录与账号安全。昵称、家庭身份和预设头像用于展示，不用于自动合并账号。', '家庭名称、成员与邀请关系、家务内容、时间、时长、积分与倍率、备注、回应、成就及布局用于协作与统计。会话标识、设备描述、令牌摘要、请求 IP、时间及必要错误信息用于通信、维持会话和安全排障。请勿在备注中填写不必要的敏感信息。'],
    ['家庭内的可见范围', '成员可按权限查看昵称、头像、家务动态、时长、积分与统计；一家之主可以审核成员和管理记录。成就展示开关仅控制成就，不隐藏家务动态。邮箱和登录凭据不作为动态展示。', '请仅向信任的人分享邀请码。主动导出的内容由您选择的应用或接收者处理。退出家庭不等于注销账号，原家庭可能继续保留历史协作记录。'],
    ['服务提供方', '阿里云提供中国内地北京地域的后端与数据库服务，以及验证码邮件投递。邮件服务会处理收件邮箱、验证码邮件内容和必要投递信息；您的邮箱服务商也会处理邮件。', 'Apple 处理 Apple 登录并返回授权结果。登录令牌保存在系统 Keychain。当前 App 未接入广告追踪 SDK；本网站不使用广告、统计脚本或外部字体。', '语音输入和 Apple 付费订阅尚未开放，当前不为语音功能采集录音。新功能上线前会说明数据处理方式、更新政策并申请必要权限。Apple 授权、邮件投递及主动分享的第三方处理不保证全部在境内完成。'],
    ['保存期限与保护', c.retentionStatement, c.backupStatement, '我们通过 HTTPS、会话撤销、验证码摘要及授权凭据加密等措施保护数据，但无法保证任何系统绝对安全。'],
    ['管理信息与注销', '您可在 App 内修改资料、编辑或删除有权限的记录、调整成就展示、退出家庭及退出当前或所有设备。退出登录不会删除账号。', '永久注销路径：我的 → 账户与安全 → 永久注销账户。确认后删除账号身份、会话、个人记录及关联数据，家庭共享成就中必要的参与引用匿名化。有其他活跃成员时转移家主身份，否则家庭一并删除。本机凭据、缓存和待同步记录同时清除，注销不可恢复。', '您也可通过联系邮箱申请查阅、更正、复制、删除或撤回同意。我们仅核实处理请求所必要的信息。注销账号不会自动取消 Apple 订阅；未来开通订阅后，购买者需通过 Apple 管理。'],
    ['未成年人与政策变更', '本服务不面向儿童独立注册。不满十四周岁的未成年人应在监护人知情同意和指导下使用。请勿在共享备注中填写非必要的儿童身份、学校或位置信息。发现未经适当同意处理儿童信息时，请联系我们。', '影响您权利的重要变更会通过 App 告知，依法需要重新取得同意的会另行征求。'],
    ['运营者与联系', `个人信息处理者：${c.operator}。联系邮箱：${c.supportEmail}。请勿发送密码、验证码或完整证件照片。`],
  ];
  return [
    { slug: 'privacy', title: en ? 'Privacy policy' : '隐私政策', intro: en ? 'What we process, who can see it, and how you stay in control.' : '了解数据如何使用、谁能看见，以及您可以如何管理。', sections: privacy },
    { slug: 'terms', title: en ? 'Terms of use' : '用户协议', intro: en ? 'The essentials of using Family Guard.' : '使用家庭保卫战前，需要了解的约定。', sections: en ? [
      ['The service', `Family Guard is operated by ${c.operator} and provides chore recording, household collaboration and reports. Points and achievements have no cash value and should not be the sole measure of a person’s contribution.`],
      ['Accounts and shared households', 'Protect your credentials and join only households you are entitled to access. Different login methods do not automatically merge accounts based on names or avatars. Owners must exercise membership and record permissions responsibly.'],
      ['Your content', 'Do not post unlawful, infringing, insulting or privacy-invasive content, misuse invitations, abuse APIs or bypass permissions. You retain rights to your content and authorize processing only as needed to provide the service.'],
      ['Free and premium access', 'The planned free allowance is 8 standard chores and 2 custom chores, plus earned achievement slots. During rollout, the allowance returned by the server applies. Premium supports personal layouts, record multipliers and unlimited standard selections; custom chores have a technical safeguard of 100. Voice input is not available.', 'Paid subscriptions are not open. Future prices, periods and payments will be confirmed through Apple in-app purchase, not this website or private transfers.'],
      ['Continuity and your rights', 'Offline records remain on your device until synchronization succeeds. Check pending records before uninstalling. Maintenance, network issues or third-party services may temporarily affect availability. Material service changes and discontinuation will be handled with applicable notice, data and paid-access obligations. These terms do not exclude statutory consumer rights.'],
      ['Leaving and resolving issues', `Leaving a household, signing out and deleting an account have different consequences shown in the app. Contact ${c.supportEmail} about issues. Unresolved disputes may be brought before a competent authority under applicable law.`],
    ] : [
      ['服务内容', `家庭保卫战由 ${c.operator} 提供，用于家务记录、家庭协作与统计。积分和成就不具有现金价值，不应作为评价家庭成员付出的唯一依据。`],
      ['账号与家庭', '请保护登录凭据，仅加入有权参与的家庭。不同登录渠道不会依据昵称或头像自动合并账号。一家之主应合理使用成员审核和记录管理权限。'],
      ['内容与使用规范', '不得发布违法、侵权、侮辱或泄露隐私的内容，不得滥用接口、传播邀请码骚扰他人或绕过权限。您保留输入内容的权利，仅授权我们在提供服务所需范围内处理。'],
      ['免费与高级权益', '免费方案为 8 项基础常用家务、2 项基础自定义，并叠加成就奖励；部署过渡期以服务器返回的额度为准。高级版支持个人布局、积分倍率及不限常用选择，自定义家务有 100 项技术保护上限。语音输入尚未开放。', '付费订阅尚未开放。未来价格、周期及支付通过 Apple 内购确认，不通过网站或私人转账收款。'],
      ['服务变动与数据', '离线记录在本机等待同步，请确认同步成功后再卸载。维护、网络或第三方服务可能造成暂时不可用。重要变更或停止服务时，我们将依法履行告知、数据及已付费权益处理义务，不排除消费者法定权利。'],
      ['退出与争议', `退出家庭、退出登录和永久注销的后果不同，请阅读 App 对应提示。服务问题可联系 ${c.supportEmail}；无法协商的争议依法通过有管辖权的机构处理。`],
    ] },
    { slug: 'subscription', title: en ? 'Subscription' : '订阅说明', intro: en ? 'One household, shared premium access. Purchases are not yet open.' : '一份家庭权益，全家共享。目前尚未开放购买。', sections: en ? [
      ['Plans', 'Planned China pricing: ¥6 per month or ¥49.90 per year. Actual currency, price and billing period will be shown by App Store at confirmation. No lifetime plan or trial is offered here.'],
      ['What is included', 'Unlimited standard chore selections, member-specific layouts and record multipliers. Custom chores have a technical safeguard of 100. Voice input is planned, not an available paid benefit. Recording, household synchronization and basic statistics remain available for free.', 'Access is shared within the same in-app household, not Apple Family Sharing or multiple households. Purchase-account and household-transfer rules will be finalized before sales open.'],
      ['Renewal, restoration and cancellation', 'Subscriptions will renew for the selected period unless cancelled by Apple’s applicable deadline. Manage them in iPhone Settings → Apple Account → Subscriptions. Cancellation normally leaves access until the paid period ends; refunds are handled by Apple.', 'Restoration retrieves eligible existing purchases and requires app-account ownership verification; it does not merge accounts. Offers will use Apple’s official redemption flow. Deleting your app account does not cancel a subscription.'],
      ['When access expires', 'The planned policy preserves historical records and permanent achievement rewards. Extra enabled chores may need to be reselected within free limits, and premium editing or additions may be restricted. These flows must pass testing before purchases open.'],
    ] : [
      ['订阅方案', '拟定月度 ¥6，年度 ¥49.90。正式币种、价格和计费周期以 App Store 确认页为准。本页不提供买断、试用或直接付款。'],
      ['包含的权益', '常用家务不限选择、成员个人布局和记录积分倍率；自定义家务有 100 项技术保护上限。语音输入规划中，不属于已提供的付费功能。记录、家庭同步和基础统计免费可用。', '权益在同一 App 家庭内共享，不等于 Apple 家庭共享，也不适用于同时授予多个家庭。购买账号与换家庭规则会在开售前明确。'],
      ['续费、恢复与取消', '订阅将按选定周期自动续费。请在 Apple 要求的期限前取消，可前往 iPhone 设置 → Apple 账户 → 订阅管理。取消后通常可使用至已付费周期结束，退款由 Apple 处理。', '恢复购买需校验既有交易及 App 账号归属，不会合并账号。优惠码将使用 Apple 官方兑换流程。注销 App 账号不会取消订阅。'],
      ['到期后的数据', '计划保留历史记录与永久成就奖励。超出免费额度的项目需重新选择启用，部分新增和高级编辑受限。上述流程完成测试后才开放购买。'],
    ] },
    { slug: 'support', title: en ? 'Help & support' : '帮助与支持', intro: en ? 'A question, a problem, or feedback? Get in touch.' : '使用中遇到问题，或有想法想告诉我？', sections: en ? [
      ['Contact', c.supportEmail],
      ['Report a problem', 'Include the app version, iOS version, time, steps and a screenshot with sensitive information hidden. Never send passwords, verification codes, tokens or private keys. For content or privacy complaints, describe the issue without repeating other people’s sensitive information.'],
      ['Login and offline records', 'Check your connection and verification email. If records are waiting to sync, keep the app installed and retry after reconnecting.'],
      ['Delete an account', 'Profile → Account & Security → Delete Account. Check pending records and household ownership first. Future Apple subscriptions must be cancelled separately through Apple.'],
    ] : [
      ['联系邮箱', c.supportEmail],
      ['反馈问题时', '请附上 App 版本、iOS 版本、发生时间、操作步骤及已遮盖敏感信息的截图。不要发送密码、验证码、令牌或私钥。内容与隐私投诉请说明事项，不要重复传播他人的敏感信息。'],
      ['登录与离线记录', '请检查网络和验证码邮件。有待同步记录时不要卸载 App，联网后重试同步。'],
      ['注销账户', '我的 → 账户与安全 → 永久注销账户。请先确认待同步记录和家庭管理身份。未来 Apple 订阅需要另行通过 Apple 取消。'],
    ] },
  ];
}
